# This workflow will run tests using bun and then publish a package to npm when a release is created
# For more information see: https://bun.sh/docs/install/ci

name: Publish npm

on:
  release:
    types:
      - created

jobs:
  ci:
    uses: techeverri/techeverri-cli/.github/workflows/ci.yml@main
    permissions:
      contents: read

  publish-npm:
    needs: ci
    runs-on: macos-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: ".bun-version"
      - run: bun install
      - run: bun run build
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          registry-url: https://registry.npmjs.org/
      - run: npm publish --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
